/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Ee9c1zw/TETasI+4rbJ0fDua/Y6o3c2ZqiTnCIF6Vl7h7O/TrZNsiWkGQ2RyYAUP6sr4Us8Wvsn6sjUz7SOR7w==
 */

/* eslint-disable */
// tslint:disable

import DbChangeLogEntry, {
  DbChangeLogEntry_InsertParameters,
} from './change_log_entries';
import DbMigrationsApplied, {
  DbMigrationsApplied_InsertParameters,
} from './db_migrations_applied';
import DbGitCommit, {DbGitCommit_InsertParameters} from './git_commits';
import DbGitRef, {DbGitRef_InsertParameters} from './git_refs';
import DbGitRepository, {
  DbGitRepository_InsertParameters,
} from './git_repositories';
import DbPullRequest, {DbPullRequest_InsertParameters} from './pull_requests';
import DbReleaseDescription, {
  DbReleaseDescription_InsertParameters,
} from './release_descriptions';

interface DatabaseSchema {
  change_log_entries: {
    record: DbChangeLogEntry;
    insert: DbChangeLogEntry_InsertParameters;
  };
  db_migrations_applied: {
    record: DbMigrationsApplied;
    insert: DbMigrationsApplied_InsertParameters;
  };
  git_commits: {record: DbGitCommit; insert: DbGitCommit_InsertParameters};
  git_refs: {record: DbGitRef; insert: DbGitRef_InsertParameters};
  git_repositories: {
    record: DbGitRepository;
    insert: DbGitRepository_InsertParameters;
  };
  pull_requests: {
    record: DbPullRequest;
    insert: DbPullRequest_InsertParameters;
  };
  release_descriptions: {
    record: DbReleaseDescription;
    insert: DbReleaseDescription_InsertParameters;
  };
}
export default DatabaseSchema;

function serializeValue(
  _tableName: string,
  _columnName: string,
  value: unknown,
): unknown {
  return value;
}
export {serializeValue};
