/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: qg7LPwq7II/rks35rzxfdFZtIlVZJNKpHuLY/Jf8C3iXXPSHLThlnTVareSsZ09kBxUdzS8vwyXk/FjeGGXnug==
 */

/* eslint-disable */
// tslint:disable

import DbPullRequest from './pull_requests';

interface DbChangeLogEntry {
  body: string;
  /**
   * @default nextval('change_log_entries_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'change_log_entries_id'};
  kind: string;
  package_name: string;
  pull_request_id: DbPullRequest['id'];
  sort_order_weight: number;
  title: string;
}
export default DbChangeLogEntry;

interface DbChangeLogEntry_InsertParameters {
  body: string;
  /**
   * @default nextval('change_log_entries_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'change_log_entries_id'};
  kind: string;
  package_name: string;
  pull_request_id: DbPullRequest['id'];
  sort_order_weight: number;
  title: string;
}
export type {DbChangeLogEntry_InsertParameters};
