/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: +O3v4ZIhqi5eZ3vCy/4mFtzoIhgVY6KGZBiCqSNdvCtu4H20DHYLUYtzyPOrHlrrKeBHu2OTeKI7yOzPaEe/IQ==
 */

// eslint:disable
// tslint:disable

import type DbPullRequest from './pull_requests';

interface DbChangeLogEntry {
  body: string;
  /**
   * @default nextval('change_log_entries_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'change_log_entries_id'};
  kind: string;
  package_name: string;
  pull_request_id: DbPullRequest['id'];
  sort_order_weight: number;
  title: string;
}
export default DbChangeLogEntry;

interface ChangeLogEntries_InsertParameters {
  body: string;
  /**
   * @default nextval('change_log_entries_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'change_log_entries_id'};
  kind: string;
  package_name: string;
  pull_request_id: DbPullRequest['id'];
  sort_order_weight: number;
  title: string;
}
export type {ChangeLogEntries_InsertParameters};
