/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DYhTPxJwEau0cz6BgoOqVzD0BcEmykuW/PoQSQE07GUVb8G+zLyWYXROJeymGBnm+Jai7iwP+yGrQZ2z93+yJQ==
 */

/* eslint-disable */
// tslint:disable

interface DbMigrationsApplied {
  migration_name: string & {
    readonly __brand?: 'db_migrations_applied_migration_name';
  };
}
export default DbMigrationsApplied;

interface DbMigrationsApplied_InsertParameters {
  migration_name: string & {
    readonly __brand?: 'db_migrations_applied_migration_name';
  };
}
export type {DbMigrationsApplied_InsertParameters};
