/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Bpg3guFg98p0PF3PWsHP95UlFLA9+cbdqy8ZEukaLUV/GMH/Qta3LAZtQulX95IuLZdKB+NszGgM6hNBYq5Tdw==
 */

// eslint:disable
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbGitCommit {
  cherry_picked_from: Array<string | null> | null;
  commit_sha: string & {readonly __brand?: 'git_commits_commit_sha'};
  git_repository_id: DbGitRepository['id'];
  message: string;
  parents: Array<string | null>;
}
export default DbGitCommit;

interface GitCommits_InsertParameters {
  cherry_picked_from?: Array<string | null> | null;
  commit_sha: string & {readonly __brand?: 'git_commits_commit_sha'};
  git_repository_id: DbGitRepository['id'];
  message: string;
  parents: Array<string | null>;
}
export type {GitCommits_InsertParameters};
