/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: Up7K7XlsgTxR92dcfQtoK9TjSRIEM/DOoi6w9szH3Ct2VI4Sn4SnkBmFNpV4oTdRkohkd15aN6Cpt2lbPLb9+Q==
 */

// eslint:disable
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbGitCommit {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  graphql_id: string;
  /**
   * Have we fetched the package_manifest_records for this commit
   *
   * @default false
   */
  has_package_manifests: boolean;
  /**
   * @default nextval('git_commits_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'git_commits_id'};
  /**
   * @default true
   */
  loaded_related_data: boolean;
}
export default DbGitCommit;

interface GitCommits_InsertParameters {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  graphql_id: string;
  /**
   * Have we fetched the package_manifest_records for this commit
   *
   * @default false
   */
  has_package_manifests?: boolean;
  /**
   * @default nextval('git_commits_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'git_commits_id'};
  /**
   * @default true
   */
  loaded_related_data?: boolean;
}
export type {GitCommits_InsertParameters};
