/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: QpuPgI9RMkZgim3zO3dZGUC4Ej8KhLu0AKM97p+MSLdnID7eWQvdvFZiuzltGXaGybc8t+bKE8G3xZzriWSrww==
 */

// eslint:disable
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbGitCommitParentCursor {
  commit_graph_id: string;
  end_cursor: string;
  git_repository_id: DbGitRepository['id'];
  /**
   * @default nextval('git_commit_parent_cursors_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'git_commit_parent_cursors_id'};
}
export default DbGitCommitParentCursor;

interface GitCommitParentCursors_InsertParameters {
  commit_graph_id: string;
  end_cursor: string;
  git_repository_id: DbGitRepository['id'];
  /**
   * @default nextval('git_commit_parent_cursors_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'git_commit_parent_cursors_id'};
}
export type {GitCommitParentCursors_InsertParameters};
