/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: DhrdCFI5k9WySUBGSWeG7eb52Q1qic3jZw6tGOeZdI4QkC6DXgOda5YsHb7iSbcIBEaRc5k2T5HUVQy+NKK1cw==
 */

// eslint:disable
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbGitRepositoryAlias {
  git_repository_id: DbGitRepository['id'];
  /**
   * @default nextval('git_repository_aliases_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'git_repository_aliases_id'};
  name: string;
  owner: string;
}
export default DbGitRepositoryAlias;

interface GitRepositoryAliases_InsertParameters {
  git_repository_id: DbGitRepository['id'];
  /**
   * @default nextval('git_repository_aliases_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'git_repository_aliases_id'};
  name: string;
  owner: string;
}
export type {GitRepositoryAliases_InsertParameters};
