/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: MId20ZtvqaWy7iyJLb56UXgg56bQXFF6mqFzI1dsBcQbjg2FlCCqhPGEd6b+7LE2Tml3hrjyoiqQycOwlidP1g==
 */

// eslint:disable
// tslint:disable

import type DbGitCommit from './git_commits';

interface DbGitCommitParent {
  child_git_commit_id: DbGitCommit['id'];
  parent_git_commit_id: DbGitCommit['id'];
}
export default DbGitCommitParent;

interface GitCommitParents_InsertParameters {
  child_git_commit_id: DbGitCommit['id'];
  parent_git_commit_id: DbGitCommit['id'];
}
export type {GitCommitParents_InsertParameters};
