/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1jiszVSY74OPlfw/rza99YWntJRjJwoCOxW7kNIN/g76X/xt31IU8h6j64jmY+lCpKpvNJ1Tag1SDnR8z+kQ7g==
 */

/* eslint-disable */
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbGitRef {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  kind: string & {readonly __brand?: 'git_refs_kind'};
  name: string & {readonly __brand?: 'git_refs_name'};
  pr_number: number | null;
  pr_ref_kind: string | null;
}
export default DbGitRef;

interface DbGitRef_InsertParameters {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  kind: string & {readonly __brand?: 'git_refs_kind'};
  name: string & {readonly __brand?: 'git_refs_name'};
  pr_number?: number | null;
  pr_ref_kind?: string | null;
}
export type {DbGitRef_InsertParameters};
