/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: FhdqMs+pMKbnaSi+MX/uLuV6iS+vN2A9iUlGdGTusr7rZf2RrhY2TCm+agk7MBUJyHRCNtggNBwwCTztYM9LIw==
 */

// eslint:disable
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbGitRef {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  kind: string & {readonly __brand?: 'git_refs_kind'};
  name: string & {readonly __brand?: 'git_refs_name'};
  pr_number: number | null;
  pr_ref_kind: string | null;
}
export default DbGitRef;

interface GitRefs_InsertParameters {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  kind: string & {readonly __brand?: 'git_refs_kind'};
  name: string & {readonly __brand?: 'git_refs_name'};
  pr_number?: number | null;
  pr_ref_kind?: string | null;
}
export type {GitRefs_InsertParameters};
