/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: SLE6Sja6X8YnN1fDXnX0x/hUit55il+U37pPbGmEmewf5o9tiWwjOH4Px1DoOejhAlipif6kmSKXIdixWpuyzg==
 */

// eslint:disable
// tslint:disable

import type DbGitRepository from './git_repositories';

interface DbGitRef {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  kind: string & {readonly __brand?: 'git_refs_kind'};
  name: string & {readonly __brand?: 'git_refs_name'};
}
export default DbGitRef;

interface GitRefs_InsertParameters {
  commit_sha: string;
  git_repository_id: DbGitRepository['id'];
  kind: string & {readonly __brand?: 'git_refs_kind'};
  name: string & {readonly __brand?: 'git_refs_name'};
}
export type {GitRefs_InsertParameters};
