/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: D0iG7SVc3nTB5sxDeVRZba9Re+DLljibWKpHCGPWJ3ZFjX7sMFdjuynIBHvXO08J7N+mY7jJ8r+be95IHoi+Wg==
 */

// eslint:disable
// tslint:disable

import DbGitCommit from './git_commits';

interface DbGitCommitPullRequest {
  git_commit_id: DbGitCommit['id'];
  pull_request_id: import('./pull_requests').default['id'];
}
export default DbGitCommitPullRequest;

interface GitCommitPullRequests_InsertParameters {
  git_commit_id: DbGitCommit['id'];
  pull_request_id: import('./pull_requests').default['id'];
}
export type {GitCommitPullRequests_InsertParameters};
