/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: GyclkFcsti2mHP6xvekh7QN82piyYNh8QhD0U0mLwokAaN1tGfp30yfUVrUZnyrZj7vrpLSCoOCReXnpl8y+Cg==
 */

// eslint:disable
// tslint:disable

import DbGitCommit from './git_commits';

interface DbGitCommitStatus {
  commit_id: DbGitCommit['id'];
  description: string;
  /**
   * @default nextval('git_commit_status_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'git_commit_status_id'};
  state: string;
  url: string;
}
export default DbGitCommitStatus;

interface GitCommitStatus_InsertParameters {
  commit_id: DbGitCommit['id'];
  description: string;
  /**
   * @default nextval('git_commit_status_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'git_commit_status_id'};
  state: string;
  url: string;
}
export type {GitCommitStatus_InsertParameters};
