/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: OedG5WGezQNXLYg9AuXDnAIfiZ9B7AYOtie5/wPbDhyJ80nGQKDqNe6nIOYqnwb470OUxTELnp7Zl0C4CGkc8g==
 */

// eslint:disable
// tslint:disable

interface DbGitRepository {
  default_branch_name: string;
  graphql_id: string;
  /**
   * The databaseId from GitHub
   */
  id: number & {readonly __brand?: 'git_repositories_id'};
  /**
   * @default true
   */
  is_private: boolean;
  name: string;
  owner: string;
  pull_requests_refreshed_at: Date | null;
  tags_refreshed_at: Date | null;
}
export default DbGitRepository;

interface GitRepositories_InsertParameters {
  default_branch_name: string;
  graphql_id: string;
  /**
   * The databaseId from GitHub
   */
  id: number & {readonly __brand?: 'git_repositories_id'};
  /**
   * @default true
   */
  is_private?: boolean;
  name: string;
  owner: string;
  pull_requests_refreshed_at?: Date | null;
  tags_refreshed_at?: Date | null;
}
export type {GitRepositories_InsertParameters};
