/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JiM3tptWtn0SkpqicWv1sFtRfQjWaNH3o/qoRUlfJtQW5bNY1IQoS4hQ35DztzQUUtqcn1vnDdqckDceZd8Mzw==
 */

// eslint:disable
// tslint:disable

import DbChangeLogEntry, {
  ChangeLogEntries_InsertParameters,
} from './change_log_entries';
import DbDbMigrationsApplied, {
  DbMigrationsApplied_InsertParameters,
} from './db_migrations_applied';
import DbGitCommit, {GitCommits_InsertParameters} from './git_commits';
import DbGitRef, {GitRefs_InsertParameters} from './git_refs';
import DbGitRepository, {
  GitRepositories_InsertParameters,
} from './git_repositories';
import DbPullRequest, {PullRequests_InsertParameters} from './pull_requests';
import DbReleaseDescription, {
  ReleaseDescriptions_InsertParameters,
} from './release_descriptions';

interface DatabaseSchema {
  change_log_entries: {
    record: DbChangeLogEntry;
    insert: ChangeLogEntries_InsertParameters;
  };
  db_migrations_applied: {
    record: DbDbMigrationsApplied;
    insert: DbMigrationsApplied_InsertParameters;
  };
  git_commits: {record: DbGitCommit; insert: GitCommits_InsertParameters};
  git_refs: {record: DbGitRef; insert: GitRefs_InsertParameters};
  git_repositories: {
    record: DbGitRepository;
    insert: GitRepositories_InsertParameters;
  };
  pull_requests: {record: DbPullRequest; insert: PullRequests_InsertParameters};
  release_descriptions: {
    record: DbReleaseDescription;
    insert: ReleaseDescriptions_InsertParameters;
  };
}
export default DatabaseSchema;

function serializeValue(
  _tableName: string,
  _columnName: string,
  value: unknown,
): unknown {
  return value;
}
export {serializeValue};
