/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: hYQZWBGlMHv+XDXcx2pGGia7CGtVArZAHK2Rg/IPID6CzWQT64ArC4hJ5fJ9mqm1PpwxCwQn1tZ92/Ecf4nGAg==
 */

// eslint:disable
// tslint:disable

import DbGitCommit from './git_commits';
import DbPackageDependencyRecordsKind from './package_dependency_records_kinds';

interface DbPackageDependencyRecord {
  dependency_name: string;
  git_commit_id: DbGitCommit['id'];
  /**
   * @default nextval('package_dependency_records_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'package_dependency_records_id'};
  kind: DbPackageDependencyRecordsKind['id'];
  package_name: string;
}
export default DbPackageDependencyRecord;

interface PackageDependencyRecords_InsertParameters {
  dependency_name: string;
  git_commit_id: DbGitCommit['id'];
  /**
   * @default nextval('package_dependency_records_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'package_dependency_records_id'};
  kind: DbPackageDependencyRecordsKind['id'];
  package_name: string;
}
export type {PackageDependencyRecords_InsertParameters};
