/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: JWKbRlAdEpeJ8+YHLcKgfYxsgvMdjecFsPH6QaiWXNQkJG2UTow1IKRFhe4/iGnoUEH/ILpGFuuZ8K7z7kE1RA==
 */

/* eslint-disable */
// tslint:disable

import DbGitRepository from './git_repositories';

interface DbReleaseDescription {
  current_version: string;
  git_repository_id: DbGitRepository['id'];
  /**
   * @default nextval('release_descriptions_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'release_descriptions_id'};
  package_name: string;
  release_description: string;
  updated_at: Date;
}
export default DbReleaseDescription;

interface DbReleaseDescription_InsertParameters {
  current_version: string;
  git_repository_id: DbGitRepository['id'];
  /**
   * @default nextval('release_descriptions_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'release_descriptions_id'};
  package_name: string;
  release_description: string;
  updated_at: Date;
}
export type {DbReleaseDescription_InsertParameters};
