/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 9hE/PwYh+vDjTbbNMZVGe15Gj+/2T1b/x8DIbbXg1P4r0F+M1ksXGrn/Q4EZUC4d+2XsA87t9j0haO6kQE6F7g==
 */

// eslint:disable
// tslint:disable

import DbChangeLogEntryKind from './change_log_entry_kinds';
import DbPullRequest from './pull_requests';

interface DbChangeLogEntry {
  body: string;
  /**
   * @default nextval('change_log_entries_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'change_log_entries_id'};
  kind: DbChangeLogEntryKind['id'];
  package_name: string;
  pull_request_id: DbPullRequest['id'];
  sort_order_weight: number;
  title: string;
}
export default DbChangeLogEntry;

interface ChangeLogEntries_InsertParameters {
  body: string;
  /**
   * @default nextval('change_log_entries_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'change_log_entries_id'};
  kind: DbChangeLogEntryKind['id'];
  package_name: string;
  pull_request_id: DbPullRequest['id'];
  sort_order_weight: number;
  title: string;
}
export type {ChangeLogEntries_InsertParameters};
