/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: qBrTX8VB0AjhZL7XxWySGDA4Ien0qfIbGaAB7M2RCgbn3sFA0XFI1uf4JkHfWenFaiIgm7fET+uXg5CNHqSi2w==
 */

// eslint:disable
// tslint:disable

interface DbChangeLogEntryKind {
  id: import('rollingversions/lib/types/PullRequestState').ChangeType
}
export default DbChangeLogEntryKind;

interface ChangeLogEntryKinds_InsertParameters {
  id: import('rollingversions/lib/types/PullRequestState').ChangeType
}
export type {ChangeLogEntryKinds_InsertParameters}
