/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: O+H/UcS/IWCTaPEohHB8rXfzQPL9LroGsCzCyPLy1ccE70S56fv7PeMqM8Od8xn/OZZo/XQ9BdNrIEJMzDcEoQ==
 */

// eslint:disable
// tslint:disable

interface DbChangeLogEntryKind {
  id: string & {readonly __brand?: 'change_log_entry_kinds_id'}
}
export default DbChangeLogEntryKind;

interface ChangeLogEntryKinds_InsertParameters {
  id: string & {readonly __brand?: 'change_log_entry_kinds_id'}
}
export type {ChangeLogEntryKinds_InsertParameters}
