/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: HDfsBpPXwDlPdS7sL06qgaMutQmKyXb3N4LxBy265nBV/0PMfWp/Fl7K0Q5ky7pJjnHogC0JYgGi89Wj10bWFQ==
 */

// eslint:disable
// tslint:disable

interface DbGitRepository {
  default_branch_name: string
  graphql_id: string
  /**
   * The databaseId from GitHub
   */
  id: number & {readonly __brand?: 'git_repositories_id'}
  name: string
  owner: string
}
export default DbGitRepository;

interface GitRepositories_InsertParameters {
  default_branch_name: string
  graphql_id: string
  /**
   * The databaseId from GitHub
   */
  id: number & {readonly __brand?: 'git_repositories_id'}
  name: string
  owner: string
}
export type {GitRepositories_InsertParameters}
