/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: iIYZ5GOLpokx19+yLg07XS7fV487rp+FgKrJMWBswAzY9spMVPY6nX1kqbTCy5qhHBKesgjwx3U/SuKCiNZz/g==
 */

// eslint:disable
// tslint:disable

import DbGitCommit from './git_commits'

interface DbGitCommitPullRequest {
  git_commit_id: DbGitCommit['id']
  pull_request_id: number & {readonly __brand?: 'git_commit_pull_requests_pull_request_id'}
}
export default DbGitCommitPullRequest;

interface GitCommitPullRequests_InsertParameters {
  git_commit_id: DbGitCommit['id']
  pull_request_id: number & {readonly __brand?: 'git_commit_pull_requests_pull_request_id'}
}
export type {GitCommitPullRequests_InsertParameters}
