/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: 1qzwUWKpyimnttMgFaq5NG5rjPh0JJ6f9MnCfkzbx3RI1zsPH3x1LMsLEh30HF93Qc2NQ90AavdR8zqh9tcqRA==
 */

// eslint:disable
// tslint:disable

interface DbPackageDependencyRecordsKind {
  id: string & {readonly __brand?: 'package_dependency_records_kinds_id'}
}
export default DbPackageDependencyRecordsKind;

interface PackageDependencyRecordsKinds_InsertParameters {
  id: string & {readonly __brand?: 'package_dependency_records_kinds_id'}
}
export type {PackageDependencyRecordsKinds_InsertParameters}
