/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: YhIvO3+kFeHTtm3lm+FmVcdkajiFq67yvHjMzAZuEwAZRQQk7jwPcuGngmNZQmH7tkQCpn7WOFxCuJH6gYAuEw==
 */

// eslint:disable
// tslint:disable

import DbGitCommit from './git_commits'
import DbPublishTarget from './publish_targets'

interface DbPackageManifestRecord {
  file_path: string
  git_commit_id: DbGitCommit['id']
  /**
   * @default nextval('package_manifest_records_id_seq'::regclass)
   */
  id: number & {readonly __brand?: 'package_manifest_records_id'}
  /**
   * @default false
   */
  not_to_be_published: boolean
  package_name: string
  publish_access: string
  publish_target: DbPublishTarget['id']
  target_config: any
}
export default DbPackageManifestRecord;

interface PackageManifestRecords_InsertParameters {
  file_path: string
  git_commit_id: DbGitCommit['id']
  /**
   * @default nextval('package_manifest_records_id_seq'::regclass)
   */
  id?: number & {readonly __brand?: 'package_manifest_records_id'}
  /**
   * @default false
   */
  not_to_be_published?: boolean
  package_name: string
  publish_access: string
  publish_target: DbPublishTarget['id']
  target_config: any
}
export type {PackageManifestRecords_InsertParameters}
