/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yrfJqzJADQIbPQTxZUA4moX0Nj9i+I8H1fo5gX4WkflGhZJKLE94i+C04pXbZ3FcsTcI0YW/DrMd9ZO/kmf6mw==
 */

// eslint:disable
// tslint:disable

interface DbPackageDependencyRecordsKind {
  id: 'required' | 'optional' | 'development'
}
export default DbPackageDependencyRecordsKind;

interface PackageDependencyRecordsKinds_InsertParameters {
  id: 'required' | 'optional' | 'development'
}
export type {PackageDependencyRecordsKinds_InsertParameters}
