/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: vfD5u1VQk9Dl6yFlFThz0nwSaVn2D8ZPgdJps2UIbAB7lkQenSEakol6nXgoydAGg1Ytej5btcPsAlYpL5N6vg==
 */

// eslint:disable
// tslint:disable

interface DbPublishTarget {
  id: string & {readonly __brand?: 'publish_targets_id'};
}
export default DbPublishTarget;

interface PublishTargets_InsertParameters {
  id: string & {readonly __brand?: 'publish_targets_id'};
}
export type {PublishTargets_InsertParameters};
